eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      routes:
        - id: portfolio-service
          uri:
            lb://portfolio-service
          predicates:
            - Path=/portfolio/**

        - id: stock-service
          uri:
            lb://stock-service
          predicates:
            - Path=/stocks/**

        - id: mutual-fund-service
          uri:
            lb://mutual-fund-service
          predicates:
            - Path=/mutualfund/**